Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -10,9 +10,33 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
+  check:
+   runs-on: ubuntu-latest
+   permissions:
+      contents: read
+      packages: write
+   steps:
+    - name: Check version
+      run: |
+        sudo apt-get update
+        sudo apt-get -y install libxml2-utils
+        # 获取 pom.xml 中的版本号，并去掉可能的 'v' 前缀
+        POM_VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml | sed 's/^v//')
+        # 获取最近的发布版本号
+        RELEASE_VERSION=$(gh api repos/${{ github.repository }}/releases/latest | jq -r .tag_name | sed 's/^v//')
+        echo "$POM_VERSION"
+        echo "$RELEASE_VERSION"
+        # 版本号对比
+        if [ "$POM_VERSION" != "$RELEASE_VERSION" ]; then
+          echo "Error: pom.xml version ($POM_VERSION) does not match the latest release version ($RELEASE_VERSION)."
+          exit 1
+        fi
+      env:
+        GH_TOKEN: ${{ github.token }}        
 
+  build:
     runs-on: ubuntu-latest
+    needs: check
     permissions:
       contents: read
       packages: write
@@ -40,20 +64,4 @@ jobs:
         run: |
           gpg -vvv --list-keys && gpg -vvv --list-secret-keys
 
-      - name: Check version
-        run: |
-          sudo apt-get update
-          sudo apt-get -y install libxml2-utils
-          # 获取 pom.xml 中的版本号，并去掉可能的 'v' 前缀
-          POM_VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml | sed 's/^v//')
-          # 获取最近的发布版本号
-          RELEASE_VERSION=$(gh api repos/${{ github.repository }}/releases/latest | jq -r .tag_name | sed 's/^v//')
-          echo "$POM_VERSION"
-          echo "$RELEASE_VERSION"
-          # 版本号对比
-          if [ "$POM_VERSION" != "$RELEASE_VERSION" ]; then
-            echo "Error: pom.xml version ($POM_VERSION) does not match the latest release version ($RELEASE_VERSION)."
-            exit 1
-          fi
-        env:
-          GH_TOKEN: ${{ github.token }}
+
